### ISSUE TITLE
Track HTTPS availability of node.deviceproof.org

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#168]
While running `/opt/letsencrypt/letsencrypt-auto`, Nginx Web Server plugin is not working:
```
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for node.deviceproof.org
nginx: [error] invalid PID number "" in "/run/nginx.pid"
Cleaning up challenges
nginx: [error] invalid PID number "" in "/run/nginx.pid"
...
nginx restart failed:
```

**Comment by jserv** [comment]
After apply security fixes and rebooting, nginx works again. However, it implies the lack of sanity checks of HTTPS enforcement for available machine. We still have to figure out the solutions.

**Comment by ender503** [comment]
Because the `https://node.deviceproof.org` is IRI API endpoint, we could furthermore test the IRI service with `getNodeInfo`, so we are using the blackbox_exporter with Prometheus to check the HTTPS is reachable.

The following configuration is added to the blackbox_exporter:
```yaml
# blackbox_exporter.yml
  iri_get_node_info:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Content-Type: application/json
        X-IOTA-API-Version: 1
      body: '{"command": "getNodeInfo"}'
```

And we are using this module to testing the https://node.deviceproof.org
```yaml
# prometheus.yml
  - job_name: 'iri_api_probe'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [iri_get_node_info]
    static_configs:
      - targets:
        - http://node.deviceproof.org
        - https://node.deviceproof.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: node0.puyuma.org:9115
```
Grafana Dashboard:

![image](https://user-images.githubusercontent.com/1849431/59992199-235ebb00-967d-11e9-93c8-5701ee8d49d8.png)
